// build.zig - Builds the osOS kernel for various architectures
// Copyright (C) 2025 Sebastian Pineda (spineda.wpi.alum@gmail.com)
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

const std = @import("std");
const builtin = @import("builtin");
const build_helpers = @import("build_helpers/root.zig");

const BuildTool = build_helpers.BuildTool;

const CommonModule = struct {
    name: []const u8,
    module: *std.Build.Module,

    // Some tests are not yet supported to run on my OS just yet, and need
    // to happen on the native target.
    test_artifact: *std.Build.Step.Compile,

    doc_artifact: *std.Build.Step.Compile,
    emitted_doc_directory: std.Build.LazyPath,

    pub fn create(
        b: *std.Build,
        name: []const u8,
        root_source_file: []const u8,
        test_target: std.Build.ResolvedTarget,
    ) CommonModule {
        const root = b.path(root_source_file);
        const actual_module = b.createModule(.{
            .root_source_file = root,
        });
        const doc_directory, const doc_artifact, const test_artifact = doc: {
            const native_target = builtin.target;
            const native_target_query = std.Target.Query.fromTarget(
                &native_target,
            );
            const resolved_native_target = b.resolveTargetQuery(
                native_target_query,
            );
            // The library object shouldn't be used by anyone, so encapsulate
            // it here
            const doc_mod = b.createModule(.{
                .root_source_file = root,
                .target = resolved_native_target,
            });
            const doc_lib = b.addLibrary(.{
                .name = name,
                .root_module = doc_mod,
            });

            const test_mod = b.createModule(.{
                .root_source_file = root,
                .target = test_target,
            });

            break :doc .{
                doc_lib.getEmittedDocs(),
                doc_lib,
                b.addTest(.{
                    .root_module = test_mod,
                }),
            };
        };

        return .{
            .name = name,
            .module = actual_module,
            .doc_artifact = doc_artifact,
            .emitted_doc_directory = doc_directory,
            .test_artifact = test_artifact,
        };
    }
};

const FileErrors = std.Io.File.OpenError || std.Io.File.Writer.EndError;
const IoErrors = std.Io.Writer.Error || FileErrors;
const Err = std.mem.Allocator.Error || IoErrors;

const autogen_lines = [_][]const u8{
    "// !!!!!!!!!!!!!!!!!!!!!!! ATTENTION !!!!!!!!!!!!!!!!!!!!!!\n",
    "// ! THIS FILE HAS BEEN GENERATED BY THE ZIG BUILD SYSTEM !\n",
    "// ! DON'T MAKE CHANGES TO THIS FILE NOR COMMIT IT TO GIT !\n",
    "// !   ANY CHANGES SHOULD BE MADE DIRECTLY IN BUILD.ZIG   !\n",
    "// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
};

const Steps = struct {
    build_all: *std.Build.Step,
    build_docs: *std.Build.Step,
    build_iso: *std.Build.Step,
    build_kernel: *std.Build.Step,
    build_shell: *std.Build.Step,
    run: *std.Build.Step,
    test_: *std.Build.Step,

    fn init(b: *std.Build) Steps {
        return .{
            .build_all = b.step(
                "all",
                "Build the Kernel for all supported architectures",
            ),
            .build_docs = b.step(
                "doc_site",
                "Build all docs and tie them together with the landing page",
            ),
            .build_iso = b.step("iso", "Build the x86 ISO disc image"),
            .build_kernel = b.step(
                "kernel",
                "Build (just) the kernel for just the specified target",
            ),
            .build_shell = b.step("shell", "build the userland shell"),
            .run = b.step(
                "run",
                "Boot kernel for specified target (x86 by default)",
            ),
            .test_ = b.step(
                "test",
                "Run arch-agnostic unit tests (Runnable from any host)",
            ),
        };
    }
};

const kernel_name = "osOS.elf";

const Targets = struct {
    x86: std.Target.Query,
    riscv32: std.Target.Query,

    fn init() Targets {
        return .{
            .x86 = .{
                .cpu_arch = .x86,
                .os_tag = .freestanding,
                .abi = .none,
                // remove features not guaranteed to exist on the original i386
                .cpu_features_sub = std.Target.x86.featureSet(&.{
                    .mmx,
                    .sse,
                    .sse2,
                    .sse3,
                    .sse4_1,
                    .sse4_2,
                    .sse4a,
                    .sse_unaligned_mem,
                    .ssse3,
                    .avx,
                }),
            },
            .riscv32 = .{
                .cpu_arch = .riscv32,
                .os_tag = .freestanding,
                .abi = .none,
            },
        };
    }
};

const BuildConfig = struct {
    run_info: RunInfo,
    boot_info: build_helpers.enums.BootLoadInfo,
    runtime_tests: RuntimeTestInfo,
    tool_info: ToolInfo,

    const RunInfo = struct {
        target: build_helpers.enums.SupportedTarget,
        use_debugger: bool,
        emulator: build_helpers.enums.Emulator,
    };
    const RuntimeTestInfo = struct {
        test_panic: bool,
        test_illegal_instruction: bool,
    };
    const ToolInfo = struct {
        build_bochs: bool,
        build_schilytools: bool,
    };

    fn init(
        source: []const u8,
        allocator: std.mem.Allocator,
        io: std.Io,
    ) !BuildConfig {
        const cwd: std.Io.Dir = .cwd();
        const file = try cwd.openFile(io, source, .{});

        var reader_buf: [4096]u8 = undefined;
        const file_reader = file.reader(io, &reader_buf);
        var reader = file_reader.interface;

        var file_contents: std.ArrayList(u8) = .empty;

        var keep_going: bool = true;
        var content_buf: [4096]u8 = @splat(0);
        while (keep_going) {
            const amount_read = try reader.readSliceShort(&content_buf);
            try file_contents.appendSlice(allocator, content_buf[0..amount_read]);
            keep_going = (amount_read >= content_buf.len);
        }

        try file_contents.append(allocator, 0);
        return try std.zon.parse.fromSlice(
            BuildConfig,
            allocator,
            @ptrCast(file_contents.items),
            null,
            .{},
        );
    }
};

// Although this function looks imperative, note that its job is to
// declaratively construct a build graph that will be executed by an external
// runner.
pub fn build(b: *std.Build) Err!void {
    const optimize = b.standardOptimizeOption(.{});
    const test_target = b.standardTargetOptions(.{});

    const target_info: Targets = .init();
    const x86_target = b.resolveTargetQuery(target_info.x86);
    const riscv32_target = b.resolveTargetQuery(target_info.riscv32);

    var threaded_io: std.Io.Threaded = .init(b.allocator, .{});
    const io: std.Io = threaded_io.io();

    const zigver = builtin.zig_version;
    std.debug.print(
        "building with zig version: {}.{}.{}\n",
        .{ zigver.major, zigver.minor, zigver.patch },
    );

    std.debug.print("*************** Build time options **************\n", .{});
    const build_options: build_helpers.BuildOptions = .init(b);
    inline for (comptime std.meta.fieldNames(build_helpers.BuildOptions)) |option_name| {
        const option = @field(build_options, option_name);
        std.debug.print("Option: {s}\n", .{option_name});
        std.debug.print("\tValue: {}\n\n", .{option});
    }
    std.debug.print("*************************************************\n", .{});

    //**************************************************************************
    //                               Option Setup                              *
    //**************************************************************************

    const boot_options = b.addOptions();
    switch (build_options.boot_info) {
        .limine => |limine_boot| {
            boot_options.addOption(
                @TypeOf(limine_boot),
                "boot_specification",
                limine_boot,
            );
        },
        .grub_legacy => |grub_boot| {
            boot_options.addOption(
                @TypeOf(grub_boot),
                "boot_specification",
                grub_boot,
            );
        },
    }

    const test_options = b.addOptions();
    test_options.addOption(bool, "test_panic", build_options.test_panic);
    test_options.addOption(bool, "test_ill", build_options.test_illegal_instruction);

    const depbochs: ?*std.Build.Dependency = dep: {
        if (build_options.build_bochs) {
            break :dep b.lazyDependency(
                "bochs_zig",
                .{
                    .optimize = std.builtin.OptimizeMode.ReleaseFast,
                    .@"with-sdl2" = true,
                    .@"enable-debugger" = build_options.use_debugger,
                },
            );
        } else {
            break :dep null;
        }
    };

    const dep_schilytools: ?*std.Build.Dependency = dep: {
        if (build_options.build_schilytools) {
            break :dep b.lazyDependency(
                "schilytools_zig",
                .{
                    .optimize = std.builtin.OptimizeMode.ReleaseFast,
                },
            );
        } else {
            break :dep null;
        }
    };

    const build_steps: Steps = .init(b);

    //**************************************************************************
    //                               Module Setup                              *
    //**************************************************************************

    //* ******************************* Shared ******************************* *

    const SharedModules = struct {
        osformat: CommonModule,
        osmemory: CommonModule,
        osprocess: CommonModule,
        osboot: CommonModule,
        oshal: CommonModule,
        osstdlib: CommonModule,
        oscontainers: CommonModule,
        osdtb: CommonModule,

        /// This is special
        kmain: CommonModule,
    };

    const shared_modules: SharedModules = .{
        .osformat = .create(b, "osformat", "format/root.zig", test_target),
        .osmemory = .create(b, "osmemory", "memory/root.zig", test_target),
        .osprocess = .create(b, "osprocess", "process/root.zig", test_target),
        .osboot = .create(b, "osboot", "boot_utilities/bootutils.zig", test_target),
        .oshal = .create(b, "oshal", "HAL/root.zig", test_target),
        .osstdlib = .create(b, "osstdlib", "userland/stdlib/root.zig", test_target),
        .oscontainers = .create(b, "oscontainers", "containers/root.zig", test_target),
        .osdtb = .create(b, "osdtb", "dtb/root.zig", test_target),
        .kmain = .create(b, "kmain", "kmain/kmain.zig", test_target),
    };

    inline for (comptime std.meta.fieldNames(SharedModules)) |field_name| {
        const step = b.step(field_name, "Build " ++ field_name ++ " module");
        const mod: CommonModule = @field(shared_modules, field_name);
        step.dependOn(&mod.test_artifact.step);
    }

    shared_modules.oshal.module.addImport(
        shared_modules.osformat.name,
        shared_modules.osformat.module,
    );
    shared_modules.oshal.module.addImport(
        shared_modules.osprocess.name,
        shared_modules.osprocess.module,
    );

    const exebochs: ?*std.Build.Step.Compile = bochs: {
        if (!build_options.build_bochs) {
            break :bochs null;
        } else if (depbochs) |dep| {
            break :bochs dep.artifact("bochs");
        } else {
            break :bochs null;
        }
    };

    const exe_mkisofs: ?*std.Build.Step.Compile = blk: {
        if (build_options.build_schilytools) {
            if (dep_schilytools) |dep| {
                break :blk dep.artifact("mkisofs");
            } else {
                break :blk null;
            }
        } else {
            break :blk null;
        }
    };

    const UserlandModules = struct {
        sys: CommonModule,
    };
    const userland_modules: UserlandModules = .{
        .sys = .create(b, "sys", "userland/stdlib/root.zig", test_target),
    };
    const shell_module = b.createModule(.{
        .root_source_file = b.path("userland/shell/main.zig"),
        .target = b.resolveTargetQuery(.{
            .cpu_arch = switch (build_options.default_run_target) {
                .x86 => .x86,
                .riscv32 => .riscv32,
            },
            .os_tag = .freestanding,
            .abi = .none,
        }),
        .optimize = optimize,
        .strip = false,
    });
    shell_module.addImport(userland_modules.sys.name, userland_modules.sys.module);
    userland_modules.sys.module.addAnonymousImport(
        "syscall_table",
        .{
            .root_source_file = switch (build_options.default_run_target) {
                .x86 => b.path("arch/x86/interrupts/syscall.zon"),
                else => b.path("arch/riscv32/interrupts/syscall.zon"),
            },
        },
    );

    //* *************************** RISC Specific **************************** *
    const RiscV32Modules = struct {
        asm_module: CommonModule,
        tty_module: CommonModule,
        boot_info: CommonModule,
    };
    const riscv32_modules: RiscV32Modules = .{
        .asm_module = .create(b, "riscv32asm", "arch/riscv32/asm/root.zig", test_target),
        .tty_module = .create(b, "riscv32tty", "arch/riscv32/tty/root.zig", test_target),
        .boot_info = .create(b, "BootInfo", "arch/riscv32/boot_info/root.zig", test_target),
    };

    riscv32_modules.tty_module.module.addImport(
        shared_modules.osformat.name,
        shared_modules.osformat.module,
    );
    riscv32_modules.boot_info.module.addImport(
        shared_modules.osprocess.name,
        shared_modules.osprocess.module,
    );

    const riscv32_module = b.createModule(.{
        .root_source_file = b.path("arch/riscv32/entry.zig"),
        .target = riscv32_target,
        .optimize = optimize,
        .strip = false,
        .single_threaded = false,
    });
    riscv32_module.addImport(
        shared_modules.osdtb.name,
        shared_modules.osdtb.module,
    );
    riscv32_module.addImport(
        riscv32_modules.tty_module.name,
        riscv32_modules.tty_module.module,
    );
    riscv32_module.addImport(
        riscv32_modules.boot_info.name,
        riscv32_modules.boot_info.module,
    );
    riscv32_module.addImport(
        riscv32_modules.asm_module.name,
        riscv32_modules.asm_module.module,
    );
    riscv32_module.addImport(
        shared_modules.osformat.name,
        shared_modules.osformat.module,
    );
    riscv32_module.addImport(
        shared_modules.osmemory.name,
        shared_modules.osmemory.module,
    );
    riscv32_module.addImport(
        shared_modules.osprocess.name,
        shared_modules.osprocess.module,
    );
    riscv32_module.addImport(
        shared_modules.oshal.name,
        shared_modules.oshal.module,
    );

    //* *************************** x86 Specific ***************************** *
    const X86Modules = struct {
        asm_module: CommonModule,
        io_module: CommonModule,
        memory_module: CommonModule,
        interrupts_module: CommonModule,
        boot_info: CommonModule,
    };
    const x86_modules: X86Modules = .{
        .asm_module = .create(b, "x86asm", "arch/x86/asm/root.zig", test_target),
        .io_module = .create(b, "x86io", "arch/x86/io/root.zig", test_target),
        .memory_module = .create(b, "x86memory", "arch/x86/memory/root.zig", test_target),
        .interrupts_module = .create(b, "x86interrupts", "arch/x86/interrupts/root.zig", test_target),
        .boot_info = .create(b, "BootInfo", "arch/x86/boot_info/root.zig", test_target),
    };

    x86_modules.boot_info.module.addImport(
        x86_modules.memory_module.name,
        x86_modules.memory_module.module,
    );
    x86_modules.boot_info.test_artifact.root_module.addImport(
        x86_modules.memory_module.name,
        x86_modules.memory_module.test_artifact.root_module,
    );
    x86_modules.boot_info.doc_artifact.root_module.addImport(
        x86_modules.memory_module.name,
        x86_modules.memory_module.doc_artifact.root_module,
    );
    x86_modules.boot_info.module.addImport(
        shared_modules.osprocess.name,
        shared_modules.osprocess.module,
    );
    x86_modules.boot_info.module.addImport(
        shared_modules.osmemory.name,
        shared_modules.osmemory.module,
    );
    x86_modules.boot_info.test_artifact.root_module.addImport(
        shared_modules.osmemory.name,
        shared_modules.osmemory.test_artifact.root_module,
    );

    x86_modules.io_module.module.addImport(
        x86_modules.asm_module.name,
        x86_modules.asm_module.module,
    );
    x86_modules.io_module.module.addImport(
        shared_modules.osformat.name,
        shared_modules.osformat.module,
    );

    x86_modules.memory_module.module.addImport(
        x86_modules.asm_module.name,
        x86_modules.asm_module.module,
    );
    x86_modules.memory_module.test_artifact.root_module.addImport(
        x86_modules.asm_module.name,
        x86_modules.asm_module.test_artifact.root_module,
    );
    x86_modules.memory_module.module.addImport(
        x86_modules.boot_info.name,
        x86_modules.boot_info.module,
    );
    x86_modules.memory_module.test_artifact.root_module.addImport(
        x86_modules.boot_info.name,
        x86_modules.boot_info.test_artifact.root_module,
    );
    x86_modules.memory_module.module.addImport(
        shared_modules.osmemory.name,
        shared_modules.osmemory.module,
    );
    x86_modules.memory_module.test_artifact.root_module.addImport(
        shared_modules.osmemory.name,
        shared_modules.osmemory.test_artifact.root_module,
    );

    x86_modules.interrupts_module.module.addImport(
        x86_modules.asm_module.name,
        x86_modules.asm_module.module,
    );
    x86_modules.interrupts_module.module.addImport(
        x86_modules.io_module.name,
        x86_modules.io_module.module,
    );
    x86_modules.interrupts_module.module.addImport(
        shared_modules.osformat.name,
        shared_modules.osformat.module,
    );
    x86_modules.interrupts_module.module.addImport(
        x86_modules.memory_module.name,
        x86_modules.memory_module.module,
    );
    x86_modules.interrupts_module.module.addImport(
        shared_modules.oscontainers.name,
        shared_modules.oscontainers.module,
    );

    const x86_module = b.createModule(.{
        .root_source_file = b.path("arch/x86/entry.zig"),
        .target = x86_target,
        .optimize = optimize,
        .strip = false,
        .single_threaded = false,
    });
    x86_module.addImport(
        x86_modules.boot_info.name,
        x86_modules.boot_info.module,
    );
    x86_module.addImport(
        x86_modules.asm_module.name,
        x86_modules.asm_module.module,
    );
    x86_module.addImport(
        x86_modules.memory_module.name,
        x86_modules.memory_module.module,
    );
    x86_module.addImport(
        x86_modules.interrupts_module.name,
        x86_modules.interrupts_module.module,
    );
    x86_module.addImport(
        x86_modules.io_module.name,
        x86_modules.io_module.module,
    );
    x86_module.addImport(
        shared_modules.osboot.name,
        shared_modules.osboot.module,
    );
    x86_module.addImport(
        shared_modules.osprocess.name,
        shared_modules.osprocess.module,
    );
    x86_module.addImport(
        shared_modules.osformat.name,
        shared_modules.osformat.module,
    );
    x86_module.addImport(
        shared_modules.oshal.name,
        shared_modules.oshal.module,
    );
    x86_module.addImport(
        shared_modules.osmemory.name,
        shared_modules.osmemory.module,
    );
    x86_module.addOptions("bootoptions", boot_options);

    //* *************************** Doc Specific ***************************** *
    // to properly build with an opt level and root module, we need to make
    // dummy objects for freestanding modules.

    //* ******************************* kmain ******************************** *
    shared_modules.kmain.module.addImport(
        shared_modules.oshal.name,
        shared_modules.oshal.module,
    );
    shared_modules.kmain.module.addImport(
        shared_modules.osstdlib.name,
        shared_modules.osstdlib.module,
    );
    shared_modules.kmain.module.addImport(
        shared_modules.osprocess.name,
        shared_modules.osprocess.module,
    );
    shared_modules.kmain.module.addImport(
        shared_modules.osformat.name,
        shared_modules.osformat.module,
    );
    shared_modules.kmain.module.addOptions(
        "testoptions",
        test_options,
    );

    x86_module.addImport(
        shared_modules.kmain.name,
        shared_modules.kmain.module,
    );
    riscv32_module.addImport(
        shared_modules.kmain.name,
        shared_modules.kmain.module,
    );

    //**************************************************************************
    //                           Compile Step Setup                            *
    //**************************************************************************

    const Outputs = struct {
        const Self = @This();
        riscv32: std.Build.Step.InstallArtifact.Options,
        x86: std.Build.Step.InstallArtifact.Options,

        fn init() Self {
            return .{
                .riscv32 = .{
                    .dest_dir = .{
                        .override = .{
                            .custom = @tagName(std.Target.Cpu.Arch.riscv32),
                        },
                    },
                },
                .x86 = .{
                    .dest_dir = .{
                        .override = .{
                            .custom = @tagName(std.Target.Cpu.Arch.x86),
                        },
                    },
                },
            };
        }
    };
    const output_dirs: Outputs = comptime .init();

    //* ******************************* Shared ******************************* *
    const shell_exe = b.addExecutable(.{
        .name = "init",
        .root_module = shell_module,
    });
    shell_exe.entry = .{ .symbol_name = "main" };
    shell_exe.setLinkerScript(b.path("userland/shell/link.ld"));

    //* *************************** RISC Specific **************************** *
    const riscv32_exe = b.addExecutable(.{
        .name = kernel_name,
        .root_module = riscv32_module,
    });
    riscv32_exe.entry = .disabled;
    riscv32_exe.setLinkerScript(b.path("arch/riscv32/link.ld"));

    //* *************************** x86 Specific ***************************** *
    const x86_exe = b.addExecutable(.{
        .name = kernel_name,
        .root_module = x86_module,
    });
    x86_exe.entry = .disabled;
    x86_exe.setLinkerScript(b.path("arch/x86/link.ld"));

    //**************************************************************************
    //                          Install Artifact Setup                         *
    //**************************************************************************

    //* ******************************* Shared ******************************* *
    const shell_out = b.addInstallArtifact(
        shell_exe,
        switch (build_options.default_run_target) {
            .x86 => output_dirs.x86,
            .riscv32 => output_dirs.riscv32,
        },
    );
    build_steps.build_all.dependOn(&shell_out.step);
    build_steps.build_shell.dependOn(&shell_out.step);
    b.getInstallStep().dependOn(&shell_out.step);

    //* *************************** RISC Specific **************************** *
    const riscv32_out = b.addInstallArtifact(riscv32_exe, output_dirs.riscv32);
    build_steps.build_all.dependOn(&riscv32_out.step);

    //* *************************** x86 Specific ***************************** *
    const x86_out = b.addInstallArtifact(x86_exe, output_dirs.x86);
    build_steps.build_all.dependOn(&x86_out.step);

    //* *************************** Doc Specific ***************************** *

    {
        var buf: [4096]u8 = undefined;
        var dir: std.Io.Dir = std.Io.Dir.cwd();
        var output: std.Io.File = try dir.createFile(
            io,
            b.pathResolve(&.{ "docs", "zon", "config.zon" }),
            .{},
        );
        var file_writer = output.writer(io, &buf);
        defer file_writer.end() catch {};

        for (autogen_lines) |line| {
            try file_writer.interface.writeAll(line);
        }

        var zon_serializer: std.zon.Serializer = .{
            .writer = &file_writer.interface,
        };

        // Top level zon object
        var obj = try zon_serializer.beginStruct(.{});
        defer obj.end() catch {};

        const arch_info = .{
            .{
                .name = @tagName(build_helpers.enums.SupportedTarget.x86),
                .label = "x86 Documentation",
                .index_path = "x86/index.html",
                .submod_root_path = "x86modules/",
                .mod_type = X86Modules,
                .modules = x86_modules,
            },
            .{
                .name = @tagName(build_helpers.enums.SupportedTarget.riscv32),
                .label = "Risc-V32 Documentation",
                .index_path = "riscv32/index.html",
                .submod_root_path = "riscv32modules/",
                .mod_type = RiscV32Modules,
                .modules = riscv32_modules,
            },
        };

        var arch_fields = try obj.beginStructField("arch", .{});
        inline for (arch_info) |single_arch_info| {
            var single_arch_field = try arch_fields.beginStructField(
                single_arch_info.name,
                .{},
            );

            var arch_root = try single_arch_field.beginStructField("entry_module", .{});
            try arch_root.field("label", single_arch_info.label, .{});
            try arch_root.field("index_path", single_arch_info.index_path, .{});
            try arch_root.end();

            var sub_modules = try single_arch_field.beginTupleField(
                "submodules",
                .{},
            );
            inline for (comptime std.meta.fieldNames(single_arch_info.mod_type)) |field| {
                const mod: CommonModule = @field(single_arch_info.modules, field);
                var sub_module_struct = try sub_modules.beginStructField(.{});
                try sub_module_struct.field("index_path", path: {
                    var path_buf: std.ArrayList(u8) = .empty;
                    try path_buf.appendSlice(b.allocator, single_arch_info.submod_root_path);
                    try path_buf.appendSlice(b.allocator, mod.name);
                    try path_buf.appendSlice(b.allocator, "/index.html");
                    break :path path_buf.items;
                }, .{});
                try sub_module_struct.field("label", mod.name, .{});
                try sub_module_struct.end();
            }
            try sub_modules.end();
            try single_arch_field.end();
        }
        arch_fields.end() catch {};

        {
            var common = try obj.beginTupleField("common", .{});
            inline for (comptime std.meta.fieldNames(SharedModules)) |field| {
                const mod: CommonModule = @field(shared_modules, field);
                var common_submodule = try common.beginStructField(.{});
                try common_submodule.field("index_path", path: {
                    var path_buf: std.ArrayList(u8) = .empty;
                    try path_buf.appendSlice(b.allocator, "shared_modules/");
                    try path_buf.appendSlice(b.allocator, mod.name);
                    try path_buf.appendSlice(b.allocator, "/index.html");
                    break :path path_buf.items;
                }, .{});
                try common_submodule.field("label", mod.name, .{});
                try common_submodule.end();
            }
            try common.end();
        }
    }
    const moddoccopy = b.createModule(.{
        .root_source_file = b.path("docs/main.zig"),
        .optimize = .Debug,
        .target = b.resolveTargetQuery(std.Target.Query.fromTarget(&builtin.target)),
    });
    const exedoccopy = b.addExecutable(.{
        .name = "doccopy",
        .root_module = moddoccopy,
    });
    const rundoccopy = b.addRunArtifact(exedoccopy);
    rundoccopy.addArg(b.install_prefix);
    rundoccopy.step.dependOn(b.getInstallStep());

    // build all module docs before copying index.html
    const x86_install_doc = b.addInstallDirectory(.{
        .source_dir = x86_exe.getEmittedDocs(),
        .install_dir = .prefix,
        .install_subdir = "docs/x86",
    });
    inline for (comptime std.meta.fieldNames(X86Modules)) |field| {
        const member = @field(x86_modules, field);
        const install_directory = b.addInstallDirectory(.{
            .source_dir = member.emitted_doc_directory,
            .install_dir = .prefix,
            .install_subdir = buf_calc: {
                var buf: std.ArrayList(u8) = .empty;
                try buf.appendSlice(b.allocator, "docs/x86modules/");
                try buf.appendSlice(b.allocator, member.name);

                break :buf_calc buf.items;
            },
        });
        rundoccopy.step.dependOn(&install_directory.step);
    }

    const riscv32_install_doc = b.addInstallDirectory(.{
        .source_dir = riscv32_exe.getEmittedDocs(),
        .install_dir = .prefix,
        .install_subdir = "docs/" ++ @tagName(std.Target.Cpu.Arch.riscv32),
    });
    inline for (comptime std.meta.fieldNames(RiscV32Modules)) |field| {
        const member = @field(riscv32_modules, field);
        const install_directory = b.addInstallDirectory(.{
            .source_dir = member.emitted_doc_directory,
            .install_dir = .prefix,
            .install_subdir = buf_calc: {
                var buf: std.ArrayList(u8) = .empty;
                try buf.appendSlice(b.allocator, "docs/riscv32modules/");
                try buf.appendSlice(b.allocator, member.name);

                break :buf_calc buf.items;
            },
        });
        rundoccopy.step.dependOn(&install_directory.step);
    }

    inline for (comptime std.meta.fieldNames(SharedModules)) |field_name| {
        const member = @field(shared_modules, field_name);
        const install_directory = b.addInstallDirectory(.{
            .source_dir = member.emitted_doc_directory,
            .install_dir = .prefix,
            .install_subdir = "docs/shared_modules/" ++ field_name,
        });
        rundoccopy.step.dependOn(&install_directory.step);
    }

    rundoccopy.step.dependOn(&x86_install_doc.step);
    rundoccopy.step.dependOn(&riscv32_install_doc.step);

    build_steps.build_docs.dependOn(&rundoccopy.step);
    build_steps.build_all.dependOn(build_steps.build_docs);

    //**************************************************************************
    //                             Run Step Setup                              *
    //**************************************************************************

    //* *************************** RISC Specific **************************** *
    const run_riscv32 = b.addSystemCommand(&.{
        "qemu-system-riscv32",
        "-machine",
        "virt",
        "-bios",
        "default",
        "-nographic",
        "-serial",
        "mon:stdio",
        "--no-reboot",
        "-kernel",
    });
    run_riscv32.addArtifactArg(riscv32_exe);
    run_riscv32.step.dependOn(&riscv32_out.step);

    //* *************************** x86 Specific ***************************** *
    const BuildTimeTools = struct {
        setup_iso: BuildTool,
        setup_bochs: BuildTool,
    };
    const build_time_tools: BuildTimeTools = .{
        .setup_iso = .init(
            .{
                .b = b,
                .root_source_file = b.path("build_time_tools/build_iso/main.zig"),
                .name = "build_iso",
            },
        ),
        .setup_bochs = .init(
            .{
                .b = b,
                .root_source_file = b.path("build_time_tools/setup_bochs/main.zig"),
                .name = "setup_bochs",
            },
        ),
    };

    build_time_tools.setup_iso.exe.addFileArg(b.path(""));
    build_time_tools.setup_iso.exe.addArg("--kernel-src");
    build_time_tools.setup_iso.exe.addArtifactArg(x86_exe);
    build_time_tools.setup_iso.exe.addArg("--kernel-dest");
    build_time_tools.setup_iso.exe.addArg("zig-out/x86/iso/boot/"); // TODO(SEP): use special API?
    build_time_tools.setup_iso.exe.addArg("--to-create");
    build_time_tools.setup_iso.exe.addArgs(switch (build_options.boot_info) {
        .limine => &.{
            "zig-out/x86/iso/boot/limine/",
            "zig-out/x86/iso/modules/",
        },
        .grub_legacy => &.{
            "zig-out/x86/iso/boot/grub/",
            "zig-out/x86/iso/modules/",
        },
    });
    switch (build_options.boot_info) {
        .limine => {
            if (b.lazyDependency("limine", .{})) |limine| {
                build_time_tools.setup_iso.exe.addArgs(&.{
                    "--copy",
                    "arch/x86/limine/limine.conf",
                    "zig-out/x86/iso/boot/limine/limine.conf",
                });

                build_time_tools.setup_iso.exe.addArg("--copy");
                build_time_tools.setup_iso.exe.addFileArg(limine.path("limine-bios-cd.bin"));
                build_time_tools.setup_iso.exe.addArg("zig-out/x86/iso/boot/limine/limine-bios-cd.bin");

                build_time_tools.setup_iso.exe.addArg("--copy");
                build_time_tools.setup_iso.exe.addFileArg(limine.path("limine-bios.sys"));
                build_time_tools.setup_iso.exe.addArg("zig-out/x86/iso/boot/limine/limine-bios.sys");
            }
        },
        .grub_legacy => {
            build_time_tools.setup_iso.exe.addArgs(&.{
                "--copy",
                "arch/x86/grub/stage2_eltorito",
                "zig-out/x86/iso/boot/grub/stage2_eltorito",
                "--copy",
                "arch/x86/grub/menu.lst",
                "zig-out/x86/iso/boot/grub/menu.lst",
            });
        },
    }
    build_time_tools.setup_iso.exe.addArg("--copy");
    build_time_tools.setup_iso.exe.addArtifactArg(shell_exe);
    build_time_tools.setup_iso.exe.addArg("zig-out/x86/iso/modules/");

    const create_x86_iso: *std.Build.Step.Run = .create(b, "run_genisoimage");
    if (exe_mkisofs) |exe| {
        create_x86_iso.addArtifactArg(exe);
    } else {
        const prog: []const u8 = b.findProgram(&.{
            "genisoimage",
            "mkisofs",
            "genisoimage.exe",
            "mkisofs.exe",
        }, &.{}) catch |err| blk: {
            std.debug.print("WARNING: {}\n", .{err});
            break :blk "genisoimage";
        };

        create_x86_iso.addArg(prog);
    }
    create_x86_iso.addArgs(&.{
        "-R",
        "-b",
        build_options.bootBinary(),
        "-no-emul-boot",
        "-boot-load-size",
        "4",
        "-A",
        "osOS",
        "-input-charset",
        "utf8",
        "-quiet",
        "-boot-info-table",
        "-o",
        "zig-out/x86/osOS.iso",
        "zig-out/x86/iso/",
    });
    create_x86_iso.step.dependOn(&build_time_tools.setup_iso.exe.step);
    if (build_options.emulator == .bochs) {
        build_time_tools.setup_bochs.exe.addArgs(&.{
            "--dest_dir",
            "zig-out/x86/",
            "--default_config",
        });
        build_time_tools.setup_bochs.exe.addFileArg(b.path("arch/x86/bochs/bochs.config"));
        if (depbochs) |dep| {
            build_time_tools.setup_bochs.exe.addArg("--vgaromimage");
            build_time_tools.setup_bochs.exe.addFileArg(dep.path("bochs/bios/VGABIOS-lgpl-latest"));
            build_time_tools.setup_bochs.exe.addArg("--romimage");
            build_time_tools.setup_bochs.exe.addFileArg(dep.path("bochs/bios/BIOS-bochs-latest"));
        }

        create_x86_iso.step.dependOn(&build_time_tools.setup_bochs.exe.step);
    }

    switch (build_options.default_run_target) {
        .x86 => {
            build_steps.build_iso.dependOn(&create_x86_iso.step);
        },
        .riscv32 => {
            // riscv32 currently doesn't make an iso
        },
        // inline else => |arch| @panic(
        // "ISO image creation not yet supported on " ++ @tagName(arch),
        // ),
    }

    const common_x86_qemu_flags = comptime [_][]const u8{
        "qemu-system-i386",
        "-machine",
        "pc",
        "-cdrom",
        "zig-out/x86/osOS.iso",
        "-boot",
        "d",
        "-m",
        "1024",
    };

    const x86_run_qemu = b.addSystemCommand(&common_x86_qemu_flags);
    x86_run_qemu.step.dependOn(&create_x86_iso.step);

    const x86_run_qemu_debugger = b.addSystemCommand(add_debug_flags: {
        var flag_buf: std.ArrayList([]const u8) = .empty;
        try flag_buf.appendSlice(b.allocator, &common_x86_qemu_flags);
        try flag_buf.append(b.allocator, "-s");
        try flag_buf.append(b.allocator, "-S");
        break :add_debug_flags flag_buf.items;
    });
    x86_run_qemu_debugger.step.dependOn(&create_x86_iso.step);

    const x86_run_bochs: *std.Build.Step.Run = .create(b, "runbochs");
    if (build_options.emulator == .bochs) {
        if (build_options.build_bochs) {
            if (exebochs) |exe| {
                x86_run_bochs.addArtifactArg(exe);
            }
        } else {
            x86_run_bochs.addArg("bochs"); // use system installation
        }
        x86_run_bochs.addArg("-f");
        x86_run_bochs.addFileArg(b.path("zig-out/x86/bochs.config"));
        x86_run_bochs.addArg("-q");
    }

    x86_run_bochs.step.dependOn(&create_x86_iso.step);

    build_steps.build_all.dependOn(build_steps.build_iso);

    //* ************************* Generic Run Target ************************* *
    build_steps.build_kernel.dependOn(switch (build_options.default_run_target) {
        .x86 => &x86_out.step,
        .riscv32 => &riscv32_out.step,
    });
    b.getInstallStep().dependOn(build_steps.build_kernel);

    switch (build_options.default_run_target) {
        .x86 => {
            build_steps.run.dependOn(switch (build_options.emulator) {
                .bochs => &x86_run_bochs.step,
                .qemu => switch (build_options.use_debugger) {
                    false => &x86_run_qemu.step,
                    true => &x86_run_qemu_debugger.step,
                },
            });
        },
        .riscv32 => {
            build_steps.run.dependOn(&run_riscv32.step);
        },
    }

    //* ***************************** Unit Tests ***************************** *

    inline for (comptime std.meta.fieldNames(SharedModules)) |field_name| {
        const run_test = b.addRunArtifact(
            @field(shared_modules, field_name).test_artifact,
        );
        build_steps.test_.dependOn(&run_test.step);
    }
    inline for (comptime std.meta.fieldNames(X86Modules)) |field_name| {
        const run_test = b.addRunArtifact(
            @field(x86_modules, field_name).test_artifact,
        );
        build_steps.test_.dependOn(&run_test.step);
    }
    inline for (comptime std.meta.fieldNames(RiscV32Modules)) |field_name| {
        const run_test = b.addRunArtifact(
            @field(riscv32_modules, field_name).test_artifact,
        );
        build_steps.test_.dependOn(&run_test.step);
    }
}
