//! build.zig - Builds the osOS kernel for various architectures
//! Copyright (C) 2025 Sebastian Pineda (spineda.wpi.alum@gmail.com)
//!
//! This program is free software: you can redistribute it and/or modify
//! it under the terms of the GNU General Public License as published by
//! the Free Software Foundation, either version 3 of the License, or
//! (at your option) any later version.
//!
//! This program is distributed in the hope that it will be useful,
//! but WITHOUT ANY WARRANTY; without even the implied warranty of
//! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//! GNU General Public License for more details.
//!
//! You should have received a copy of the GNU General Public License
//! along with this program.  If not, see <https://www.gnu.org/licenses/>.

const std = @import("std");
const builtin = @import("builtin");
const build_helpers = @import("build_helpers/root.zig");

const BuildTool = build_helpers.BuildTool;
const OsModule = build_helpers.OsModule;
const RiscV32Modules = build_helpers.RiscV32Modules;
const X86Modules = build_helpers.X86Moudles;
const ArchAgnosticKernelModules = build_helpers.ArchAgnosticKernelModules;
const Steps = build_helpers.Steps;
const Targets = build_helpers.Targets;
const BuildTimeTools = build_helpers.BuildTimeTools;
const UserlandModules = build_helpers.UserlandModules;
const OutputDirs = build_helpers.OutputDirs;

const FileErrors = std.Io.File.OpenError || std.Io.File.Writer.EndError;
const IoErrors = std.Io.Writer.Error || FileErrors;
const Err = std.mem.Allocator.Error || IoErrors;

const autogen_lines = [_][]const u8{
    "// !!!!!!!!!!!!!!!!!!!!!!! ATTENTION !!!!!!!!!!!!!!!!!!!!!!\n",
    "// ! THIS FILE HAS BEEN GENERATED BY THE ZIG BUILD SYSTEM !\n",
    "// ! DON'T MAKE CHANGES TO THIS FILE NOR COMMIT IT TO GIT !\n",
    "// !   ANY CHANGES SHOULD BE MADE DIRECTLY IN BUILD.ZIG   !\n",
    "// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n",
};

const kernel_name = "osOS.elf";

const output_dirs: OutputDirs = .init();

// Although this function looks imperative, note that its job is to
// declaratively construct a build graph that will be executed by an external
// runner.
pub fn build(b: *std.Build) Err!void {
    const optimize = b.standardOptimizeOption(.{});
    const test_target = b.standardTargetOptions(.{});

    const target_info: Targets = .init();
    const x86_target = b.resolveTargetQuery(target_info.x86);
    const riscv32_target = b.resolveTargetQuery(target_info.riscv32);

    var threaded_io: std.Io.Threaded = .init(b.allocator, .{});
    const io: std.Io = threaded_io.io();

    std.debug.print(
        "building with zig version: {}.{}.{}\n",
        .{
            builtin.zig_version.major,
            builtin.zig_version.minor,
            builtin.zig_version.patch,
        },
    );

    std.debug.print("*************** Build time options **************\n", .{});
    const build_options: build_helpers.BuildOptions = .init(b);
    inline for (comptime std.meta.fieldNames(build_helpers.BuildOptions)) |option_name| {
        const option = @field(build_options, option_name);
        std.debug.print("Option: {s}\n", .{option_name});
        std.debug.print("\tValue: {}\n\n", .{option});
    }
    std.debug.print("*************************************************\n", .{});

    //**************************************************************************
    //                               Option Setup                              *
    //**************************************************************************

    const boot_options = b.addOptions();
    switch (build_options.boot_info) {
        .limine => |limine_boot| {
            boot_options.addOption(
                @TypeOf(limine_boot),
                "boot_specification",
                limine_boot,
            );
        },
        .grub_legacy => |grub_boot| {
            boot_options.addOption(
                @TypeOf(grub_boot),
                "boot_specification",
                grub_boot,
            );
        },
    }

    const test_options = b.addOptions();
    test_options.addOption(bool, "test_panic", build_options.test_panic);
    test_options.addOption(bool, "test_ill", build_options.test_illegal_instruction);

    const depbochs: ?*std.Build.Dependency = dep: {
        if (build_options.build_bochs) {
            break :dep b.lazyDependency(
                "bochs_zig",
                .{
                    .optimize = std.builtin.OptimizeMode.ReleaseFast,
                    .@"with-sdl2" = true,
                    .@"enable-debugger" = build_options.use_debugger,
                },
            );
        } else {
            break :dep null;
        }
    };

    const dep_schilytools: ?*std.Build.Dependency = dep: {
        if (build_options.build_schilytools) {
            break :dep b.lazyDependency(
                "schilytools_zig",
                .{
                    .optimize = std.builtin.OptimizeMode.ReleaseFast,
                },
            );
        } else {
            break :dep null;
        }
    };

    const build_steps: Steps = .init(b);

    //**************************************************************************
    //                               Module Setup                              *
    //**************************************************************************

    //* ******************************* Shared ******************************* *

    var shared_modules: ArchAgnosticKernelModules = .{
        .osformat = .init(.{
            .b = b,
            .name = "osformat",
            .root_source_file = b.path("format/root.zig"),
            .test_target = test_target,
        }),
        .osmemory = .init(.{
            .b = b,
            .name = "osmemory",
            .root_source_file = b.path("memory/root.zig"),
            .test_target = test_target,
        }),
        .osprocess = .init(.{
            .b = b,
            .name = "osprocess",
            .root_source_file = b.path("process/root.zig"),
            .test_target = test_target,
        }),
        .osboot = .init(.{
            .b = b,
            .name = "osboot",
            .root_source_file = b.path("boot_utilities/bootutils.zig"),
            .test_target = test_target,
        }),
        .oshal = .init(.{
            .b = b,
            .name = "oshal",
            .root_source_file = b.path("HAL/root.zig"),
            .test_target = test_target,
        }),
        .osstdlib = .init(.{
            .b = b,
            .name = "osstdlib",
            .root_source_file = b.path("userland/stdlib/root.zig"),
            .test_target = test_target,
        }),
        .oscontainers = .init(.{
            .b = b,
            .name = "oscontainers",
            .root_source_file = b.path("containers/root.zig"),
            .test_target = test_target,
        }),
        .osdtb = .init(.{
            .b = b,
            .name = "osdtb",
            .root_source_file = b.path("dtb/root.zig"),
            .test_target = test_target,
        }),
        .kmain = .init(.{
            .b = b,
            .name = "kmain",
            .root_source_file = b.path("kmain/kmain.zig"),
            .test_target = test_target,
        }),
    };

    shared_modules.oshal.addImportToAll(&shared_modules.osformat);
    shared_modules.oshal.addImportToAll(&shared_modules.osprocess);

    const exebochs: ?*std.Build.Step.Compile = bochs: {
        if (!build_options.build_bochs) {
            break :bochs null;
        } else if (depbochs) |dep| {
            break :bochs dep.artifact("bochs");
        } else {
            break :bochs null;
        }
    };

    const exe_mkisofs: ?*std.Build.Step.Compile = blk: {
        if (build_options.build_schilytools) {
            if (dep_schilytools) |dep| {
                break :blk dep.artifact("mkisofs");
            } else {
                break :blk null;
            }
        } else {
            break :blk null;
        }
    };

    var userland_modules: UserlandModules = .{
        .sys = .init(.{
            .b = b,
            .name = "sys",
            .root_source_file = b.path("userland/stdlib/root.zig"),
            .test_target = test_target,
        }),
        .shell = .init(.{
            .b = b,
            .name = null,
            .root_source_file = b.path("userland/shell/main.zig"),
            .test_target = test_target,
            .run_target = b.resolveTargetQuery(.{
                .cpu_arch = switch (build_options.default_run_target) {
                    .x86 => .x86,
                    .riscv32 => .riscv32,
                },
                .os_tag = .freestanding,
                .abi = .none,
            }),
            .optimize = optimize,
        }),
    };
    userland_modules.shell.addImportToAll(&userland_modules.sys);
    userland_modules.sys.addAnonymousImportToAll(
        "syscall_table",
        .{
            .root_source_file = switch (build_options.default_run_target) {
                .x86 => b.path("arch/x86/interrupts/syscall.zon"),
                else => b.path("arch/riscv32/interrupts/syscall.zon"),
            },
        },
    );

    //* *************************** RISC Specific **************************** *
    var riscv32_modules: RiscV32Modules = .{
        .asm_module = .init(.{
            .b = b,
            .name = "riscv32asm",
            .root_source_file = b.path("arch/riscv32/asm/root.zig"),
            .test_target = test_target,
        }),
        .tty_module = .init(.{
            .b = b,
            .name = "riscv32tty",
            .root_source_file = b.path("arch/riscv32/tty/root.zig"),
            .test_target = test_target,
        }),
        .boot_info = .init(.{
            .b = b,
            .name = "riscv32BootInfo",
            .root_source_file = b.path("arch/riscv32/boot_info/root.zig"),
            .test_target = test_target,
        }),
        .kernel_entry = .init(.{
            .b = b,
            .name = null,
            .root_source_file = b.path("arch/riscv32/entry.zig"),
            .test_target = test_target,
            .run_target = riscv32_target,
            .optimize = optimize,
        }),
    };

    riscv32_modules.tty_module.addImportToAll(&shared_modules.osformat);
    riscv32_modules.boot_info.addImportToAll(&shared_modules.osprocess);

    riscv32_modules.kernel_entry.addImportToAll(&shared_modules.osdtb);
    riscv32_modules.kernel_entry.addImportToAll(&riscv32_modules.tty_module);
    riscv32_modules.kernel_entry.addImportToAll(&riscv32_modules.boot_info);
    riscv32_modules.kernel_entry.addImportToAll(&riscv32_modules.asm_module);
    riscv32_modules.kernel_entry.addImportToAll(&shared_modules.osformat);
    riscv32_modules.kernel_entry.addImportToAll(&shared_modules.osmemory);
    riscv32_modules.kernel_entry.addImportToAll(&shared_modules.osprocess);
    riscv32_modules.kernel_entry.addImportToAll(&shared_modules.oshal);

    //* *************************** x86 Specific ***************************** *
    var x86_modules: X86Modules = .{
        .asm_module = .init(.{
            .b = b,
            .name = "x86asm",
            .root_source_file = b.path("arch/x86/asm/root.zig"),
            .test_target = test_target,
        }),
        .io_module = .init(.{
            .b = b,
            .name = "x86io",
            .root_source_file = b.path("arch/x86/io/root.zig"),
            .test_target = test_target,
        }),
        .memory_module = .init(.{
            .b = b,
            .name = "x86memory",
            .root_source_file = b.path("arch/x86/memory/root.zig"),
            .test_target = test_target,
        }),
        .interrupts_module = .init(.{
            .b = b,
            .name = "x86interrupts",
            .root_source_file = b.path("arch/x86/interrupts/root.zig"),
            .test_target = test_target,
        }),
        .boot_info = .init(.{
            .b = b,
            .name = "x86BootInfo",
            .root_source_file = b.path("arch/x86/boot_info/root.zig"),
            .test_target = test_target,
        }),
        .kernel_entry = .init(.{
            .b = b,
            .name = null,
            .root_source_file = b.path("arch/x86/entry.zig"),
            .test_target = test_target,
            .run_target = x86_target,
            .optimize = optimize,
        }),
    };

    x86_modules.boot_info.addImportToAll(&x86_modules.memory_module);
    x86_modules.boot_info.addImportToAll(&shared_modules.osprocess);
    x86_modules.boot_info.addImportToAll(&shared_modules.osmemory);

    x86_modules.io_module.addImportToAll(&x86_modules.asm_module);
    x86_modules.io_module.addImportToAll(&shared_modules.osformat);

    x86_modules.memory_module.addImportToAll(&x86_modules.asm_module);
    x86_modules.memory_module.addImportToAll(&x86_modules.boot_info);
    x86_modules.memory_module.addImportToAll(&shared_modules.osmemory);

    x86_modules.interrupts_module.addImportToAll(&x86_modules.asm_module);
    x86_modules.interrupts_module.addImportToAll(&x86_modules.io_module);
    x86_modules.interrupts_module.addImportToAll(&shared_modules.osformat);
    x86_modules.interrupts_module.addImportToAll(&x86_modules.memory_module);
    x86_modules.interrupts_module.addImportToAll(&shared_modules.oscontainers);

    x86_modules.kernel_entry.addImportToAll(&x86_modules.boot_info);
    x86_modules.kernel_entry.addImportToAll(&x86_modules.asm_module);
    x86_modules.kernel_entry.addImportToAll(&x86_modules.memory_module);
    x86_modules.kernel_entry.addImportToAll(&x86_modules.interrupts_module);
    x86_modules.kernel_entry.addImportToAll(&x86_modules.io_module);
    x86_modules.kernel_entry.addImportToAll(&shared_modules.osboot);
    x86_modules.kernel_entry.addImportToAll(&shared_modules.osprocess);
    x86_modules.kernel_entry.addImportToAll(&shared_modules.osformat);
    x86_modules.kernel_entry.addImportToAll(&shared_modules.oshal);
    x86_modules.kernel_entry.addImportToAll(&shared_modules.osmemory);
    x86_modules.kernel_entry.addOptionsToAll("bootoptions", boot_options);

    //* *************************** Doc Specific ***************************** *
    // to properly build with an opt level and root module, we need to make
    // dummy objects for freestanding modules.

    //* ******************************* kmain ******************************** *
    shared_modules.kmain.addImportToAll(&shared_modules.oshal);
    shared_modules.kmain.addImportToAll(&shared_modules.osstdlib);
    shared_modules.kmain.addImportToAll(&shared_modules.osprocess);
    shared_modules.kmain.addImportToAll(&shared_modules.osformat);
    shared_modules.kmain.addOptionsToAll("testoptions", test_options);

    x86_modules.kernel_entry.addImportToAll(&shared_modules.kmain);
    riscv32_modules.kernel_entry.addImportToAll(&shared_modules.kmain);

    //**************************************************************************
    //                           Compile Step Setup                            *
    //**************************************************************************

    //* ******************************* Shared ******************************* *
    const shell_exe = b.addExecutable(.{
        .name = "init",
        .root_module = userland_modules.shell.module,
    });
    shell_exe.entry = .{ .symbol_name = "main" };
    shell_exe.setLinkerScript(b.path("userland/shell/link.ld"));

    //* *************************** RISC Specific **************************** *
    const riscv32_exe = b.addExecutable(.{
        .name = kernel_name,
        .root_module = riscv32_modules.kernel_entry.module,
    });
    riscv32_exe.entry = .disabled;
    riscv32_exe.setLinkerScript(b.path("arch/riscv32/link.ld"));

    //* *************************** x86 Specific ***************************** *
    const x86_exe = b.addExecutable(.{
        .name = kernel_name,
        .root_module = x86_modules.kernel_entry.module,
    });
    x86_exe.entry = .disabled;
    x86_exe.setLinkerScript(b.path("arch/x86/link.ld"));

    //**************************************************************************
    //                          Install Artifact Setup                         *
    //**************************************************************************

    //* ******************************* Shared ******************************* *
    const shell_out = b.addInstallArtifact(
        shell_exe,
        switch (build_options.default_run_target) {
            .x86 => output_dirs.x86,
            .riscv32 => output_dirs.riscv32,
        },
    );
    build_steps.build_all.dependOn(&shell_out.step);
    b.getInstallStep().dependOn(&shell_out.step);

    //* *************************** RISC Specific **************************** *
    const riscv32_out = b.addInstallArtifact(riscv32_exe, output_dirs.riscv32);
    build_steps.build_all.dependOn(&riscv32_out.step);

    //* *************************** x86 Specific ***************************** *
    const x86_out = b.addInstallArtifact(x86_exe, output_dirs.x86);
    build_steps.build_all.dependOn(&x86_out.step);

    //* *************************** Doc Specific ***************************** *

    {
        var buf: [4096]u8 = undefined;
        var dir: std.Io.Dir = std.Io.Dir.cwd();
        var output: std.Io.File = try dir.createFile(
            io,
            b.pathResolve(&.{ "docs", "zon", "config.zon" }),
            .{},
        );
        var file_writer = output.writer(io, &buf);
        defer file_writer.end() catch {};

        for (autogen_lines) |line| {
            try file_writer.interface.writeAll(line);
        }

        var zon_serializer: std.zon.Serializer = .{
            .writer = &file_writer.interface,
        };

        // Top level zon object
        var obj = try zon_serializer.beginStruct(.{});
        defer obj.end() catch {};

        const arch_info = .{
            .{
                .name = @tagName(build_helpers.enums.SupportedTarget.x86),
                .label = "x86 Documentation",
                .index_path = "x86/index.html",
                .submod_root_path = "x86modules/",
                .mod_type = X86Modules,
                .modules = x86_modules,
            },
            .{
                .name = @tagName(build_helpers.enums.SupportedTarget.riscv32),
                .label = "Risc-V32 Documentation",
                .index_path = "riscv32/index.html",
                .submod_root_path = "riscv32modules/",
                .mod_type = RiscV32Modules,
                .modules = riscv32_modules,
            },
        };

        var arch_fields = try obj.beginStructField("arch", .{});
        inline for (arch_info) |single_arch_info| {
            var single_arch_field = try arch_fields.beginStructField(
                single_arch_info.name,
                .{},
            );

            var arch_root = try single_arch_field.beginStructField("entry_module", .{});
            try arch_root.field("label", single_arch_info.label, .{});
            try arch_root.field("index_path", single_arch_info.index_path, .{});
            try arch_root.end();

            var sub_modules = try single_arch_field.beginTupleField(
                "submodules",
                .{},
            );
            inline for (comptime std.meta.fieldNames(single_arch_info.mod_type)) |field| {
                const mod: OsModule = @field(single_arch_info.modules, field);
                if (mod.name) |name| {
                    var sub_module_struct = try sub_modules.beginStructField(.{});
                    const path: []const u8 = std.fmt.allocPrint(
                        b.allocator,
                        "{s}{s}/index.html",
                        .{
                            single_arch_info.submod_root_path,
                            name,
                        },
                    ) catch @panic("OOM");
                    try sub_module_struct.field("index_path", path, .{});
                    try sub_module_struct.field("label", name, .{});
                    try sub_module_struct.end();
                }
            }
            try sub_modules.end();
            try single_arch_field.end();
        }
        arch_fields.end() catch {};

        {
            var common = try obj.beginTupleField("common", .{});
            inline for (comptime std.meta.fieldNames(ArchAgnosticKernelModules)) |field| {
                const mod: OsModule = @field(shared_modules, field);
                if (mod.name) |name| {
                    var common_submodule = try common.beginStructField(.{});
                    const path: []const u8 = std.fmt.allocPrint(
                        b.allocator,
                        "shared_modules/{s}/index.html",
                        .{
                            name,
                        },
                    ) catch @panic("OOM");
                    try common_submodule.field("index_path", path, .{});
                    try common_submodule.field("label", mod.name, .{});
                    try common_submodule.end();
                }
            }
            try common.end();
        }
    }
    const moddoccopy = b.createModule(.{
        .root_source_file = b.path("docs/main.zig"),
        .optimize = .Debug,
        .target = b.resolveTargetQuery(std.Target.Query.fromTarget(&builtin.target)),
    });
    const exedoccopy = b.addExecutable(.{
        .name = "doccopy",
        .root_module = moddoccopy,
    });
    const rundoccopy = b.addRunArtifact(exedoccopy);
    rundoccopy.addArg(b.install_prefix);
    rundoccopy.step.dependOn(b.getInstallStep());

    // build all module docs before copying index.html
    const x86_install_doc = b.addInstallDirectory(.{
        .source_dir = x86_exe.getEmittedDocs(),
        .install_dir = .prefix,
        .install_subdir = "docs/x86",
    });
    inline for (comptime std.meta.fieldNames(X86Modules)) |field| {
        const member: OsModule = @field(x86_modules, field);
        if (member.name) |name| {
            const path = std.fmt.allocPrint(
                b.allocator,
                "docs/x86modules/{s}",
                .{name},
            ) catch @panic("OOM");
            const install_directory = b.addInstallDirectory(.{
                .source_dir = member.emitted_doc_directory,
                .install_dir = .prefix,
                .install_subdir = path,
            });
            rundoccopy.step.dependOn(&install_directory.step);
        }
    }

    const riscv32_install_doc = b.addInstallDirectory(.{
        .source_dir = riscv32_exe.getEmittedDocs(),
        .install_dir = .prefix,
        .install_subdir = "docs/" ++ @tagName(std.Target.Cpu.Arch.riscv32),
    });
    inline for (comptime std.meta.fieldNames(RiscV32Modules)) |field| {
        const member: OsModule = @field(riscv32_modules, field);
        if (member.name) |name| {
            const path = std.fmt.allocPrint(
                b.allocator,
                "docs/riscv32modules/{s}",
                .{name},
            ) catch @panic("OOM");
            const install_directory = b.addInstallDirectory(.{
                .source_dir = member.emitted_doc_directory,
                .install_dir = .prefix,
                .install_subdir = path,
            });
            rundoccopy.step.dependOn(&install_directory.step);
        }
    }

    inline for (comptime std.meta.fieldNames(ArchAgnosticKernelModules)) |field_name| {
        const member: OsModule = @field(shared_modules, field_name);
        const install_directory = b.addInstallDirectory(.{
            .source_dir = member.emitted_doc_directory,
            .install_dir = .prefix,
            .install_subdir = "docs/shared_modules/" ++ field_name,
        });
        rundoccopy.step.dependOn(&install_directory.step);
    }

    rundoccopy.step.dependOn(&x86_install_doc.step);
    rundoccopy.step.dependOn(&riscv32_install_doc.step);

    build_steps.build_docs.dependOn(&rundoccopy.step);
    build_steps.build_all.dependOn(build_steps.build_docs);

    //**************************************************************************
    //                             Run Step Setup                              *
    //**************************************************************************

    //* *************************** RISC Specific **************************** *
    const run_riscv32 = b.addSystemCommand(&.{
        "qemu-system-riscv32",
        "-machine",
        "virt",
        "-bios",
        "default",
        "-nographic",
        "-serial",
        "mon:stdio",
        "--no-reboot",
        "-kernel",
    });
    run_riscv32.addArtifactArg(riscv32_exe);
    run_riscv32.step.dependOn(&riscv32_out.step);

    //* *************************** x86 Specific ***************************** *
    const build_time_tools: BuildTimeTools = .{
        .setup_iso = .init(
            .{
                .b = b,
                .root_source_file = b.path("build_time_tools/build_iso/main.zig"),
                .name = "build_iso",
            },
        ),
        .setup_bochs = .init(
            .{
                .b = b,
                .root_source_file = b.path("build_time_tools/setup_bochs/main.zig"),
                .name = "setup_bochs",
            },
        ),
    };

    build_time_tools.setup_iso.exe.addFileArg(b.path(""));
    build_time_tools.setup_iso.exe.addArg("--kernel-src");
    build_time_tools.setup_iso.exe.addArtifactArg(x86_exe);
    build_time_tools.setup_iso.exe.addArg("--kernel-dest");
    build_time_tools.setup_iso.exe.addArg("zig-out/x86/iso/boot/"); // TODO(SEP): use special API?
    build_time_tools.setup_iso.exe.addArg("--to-create");
    build_time_tools.setup_iso.exe.addArgs(switch (build_options.boot_info) {
        .limine => &.{
            "zig-out/x86/iso/boot/limine/",
            "zig-out/x86/iso/modules/",
        },
        .grub_legacy => &.{
            "zig-out/x86/iso/boot/grub/",
            "zig-out/x86/iso/modules/",
        },
    });
    switch (build_options.boot_info) {
        .limine => {
            if (b.lazyDependency("limine", .{})) |limine| {
                build_time_tools.setup_iso.exe.addArgs(&.{
                    "--copy",
                    "arch/x86/limine/limine.conf",
                    "zig-out/x86/iso/boot/limine/limine.conf",
                });

                build_time_tools.setup_iso.exe.addArg("--copy");
                build_time_tools.setup_iso.exe.addFileArg(limine.path("limine-bios-cd.bin"));
                build_time_tools.setup_iso.exe.addArg("zig-out/x86/iso/boot/limine/limine-bios-cd.bin");

                build_time_tools.setup_iso.exe.addArg("--copy");
                build_time_tools.setup_iso.exe.addFileArg(limine.path("limine-bios.sys"));
                build_time_tools.setup_iso.exe.addArg("zig-out/x86/iso/boot/limine/limine-bios.sys");
            }
        },
        .grub_legacy => {
            build_time_tools.setup_iso.exe.addArgs(&.{
                "--copy",
                "arch/x86/grub/stage2_eltorito",
                "zig-out/x86/iso/boot/grub/stage2_eltorito",
                "--copy",
                "arch/x86/grub/menu.lst",
                "zig-out/x86/iso/boot/grub/menu.lst",
            });
        },
    }
    build_time_tools.setup_iso.exe.addArg("--copy");
    build_time_tools.setup_iso.exe.addArtifactArg(shell_exe);
    build_time_tools.setup_iso.exe.addArg("zig-out/x86/iso/modules/");

    const create_x86_iso: *std.Build.Step.Run = .create(b, "run_genisoimage");
    if (exe_mkisofs) |exe| {
        create_x86_iso.addArtifactArg(exe);
    } else {
        const prog: []const u8 = b.findProgram(&.{
            "genisoimage",
            "mkisofs",
            "genisoimage.exe",
            "mkisofs.exe",
        }, &.{}) catch |err| blk: {
            std.debug.print("WARNING: {}\n", .{err});
            break :blk "genisoimage";
        };

        create_x86_iso.addArg(prog);
    }
    create_x86_iso.addArgs(&.{
        "-R",
        "-b",
        build_options.bootBinary(),
        "-no-emul-boot",
        "-boot-load-size",
        "4",
        "-A",
        "osOS",
        "-input-charset",
        "utf8",
        "-quiet",
        "-boot-info-table",
        "-o",
        "zig-out/x86/osOS.iso",
        "zig-out/x86/iso/",
    });
    create_x86_iso.step.dependOn(&build_time_tools.setup_iso.exe.step);
    if (build_options.emulator == .bochs) {
        build_time_tools.setup_bochs.exe.addArgs(&.{
            "--dest_dir",
            "zig-out/x86/",
            "--default_config",
        });
        build_time_tools.setup_bochs.exe.addFileArg(b.path("arch/x86/bochs/bochs.config"));
        if (depbochs) |dep| {
            build_time_tools.setup_bochs.exe.addArg("--vgaromimage");
            build_time_tools.setup_bochs.exe.addFileArg(dep.path("bochs/bios/VGABIOS-lgpl-latest"));
            build_time_tools.setup_bochs.exe.addArg("--romimage");
            build_time_tools.setup_bochs.exe.addFileArg(dep.path("bochs/bios/BIOS-bochs-latest"));
        }

        create_x86_iso.step.dependOn(&build_time_tools.setup_bochs.exe.step);
    }

    switch (build_options.default_run_target) {
        .x86 => {
            build_steps.build_iso.dependOn(&create_x86_iso.step);
        },
        .riscv32 => {
            // riscv32 currently doesn't make an iso
        },
        // inline else => |arch| @panic(
        // "ISO image creation not yet supported on " ++ @tagName(arch),
        // ),
    }

    const common_x86_qemu_flags = comptime [_][]const u8{
        "qemu-system-i386",
        "-machine",
        "pc",
        "-cdrom",
        "zig-out/x86/osOS.iso",
        "-boot",
        "d",
        "-m",
        "1024",
    };

    const x86_run_qemu = b.addSystemCommand(&common_x86_qemu_flags);
    x86_run_qemu.step.dependOn(&create_x86_iso.step);

    const x86_run_qemu_debugger = b.addSystemCommand(add_debug_flags: {
        var flag_buf: std.ArrayList([]const u8) = .empty;
        try flag_buf.appendSlice(b.allocator, &common_x86_qemu_flags);
        try flag_buf.append(b.allocator, "-s");
        try flag_buf.append(b.allocator, "-S");
        break :add_debug_flags flag_buf.items;
    });
    x86_run_qemu_debugger.step.dependOn(&create_x86_iso.step);

    const x86_run_bochs: *std.Build.Step.Run = .create(b, "runbochs");
    if (build_options.emulator == .bochs) {
        if (build_options.build_bochs) {
            if (exebochs) |exe| {
                x86_run_bochs.addArtifactArg(exe);
            }
        } else {
            x86_run_bochs.addArg("bochs"); // use system installation
        }
        x86_run_bochs.addArg("-f");
        x86_run_bochs.addFileArg(b.path("zig-out/x86/bochs.config"));
        x86_run_bochs.addArg("-q");
    }

    x86_run_bochs.step.dependOn(&create_x86_iso.step);

    build_steps.build_all.dependOn(build_steps.build_iso);

    //* ************************* Generic Run Target ************************* *
    build_steps.build_kernel.dependOn(switch (build_options.default_run_target) {
        .x86 => &x86_out.step,
        .riscv32 => &riscv32_out.step,
    });
    b.getInstallStep().dependOn(build_steps.build_kernel);

    switch (build_options.default_run_target) {
        .x86 => {
            build_steps.run.dependOn(switch (build_options.emulator) {
                .bochs => &x86_run_bochs.step,
                .qemu => switch (build_options.use_debugger) {
                    false => &x86_run_qemu.step,
                    true => &x86_run_qemu_debugger.step,
                },
            });
        },
        .riscv32 => {
            build_steps.run.dependOn(&run_riscv32.step);
        },
    }

    //* ***************************** Unit Tests ***************************** *

    const testables = .{
        .{ ArchAgnosticKernelModules, &shared_modules },
        .{ X86Modules, &x86_modules },
        .{ RiscV32Modules, &riscv32_modules },
    };

    inline for (testables) |testable| {
        const Container: type, const instance = testable;
        inline for (comptime std.meta.fieldNames(Container)) |field_name| {
            const mod: OsModule = @field(instance.*, field_name);
            if (mod.name) |_| {
                build_steps.test_.dependOn(&mod.test_artifact.run.step);
            }
        }
    }
    inline for (comptime std.meta.fieldNames(BuildTimeTools)) |field_name| {
        const tool: BuildTool = @field(build_time_tools, field_name);
        if (tool.test_exe) |test_exe| {
            build_steps.test_.dependOn(&test_exe.step);
        }
    }
}
